# 路由关系表
[[routing]]
  from = "/"
  to = "homepage"
  template = "general1"
  replacement = "replacement"

[[routing]]
  from = "/task-list"
  to = "task-list"
  template = "general1"
  replacement = "replacement"
